window.CONFIG = {
    "schoolName": "SEKOLAH NUSANTARA",
    "assessmentName": "ASESMEN TENGAH SEMESTER",
    "academicYear": "2026-2027",
    "examDay": "Senin",
    "examDate": "15 Juni 2026",
    "examToken": "benar",
    "unlockToken": "salah",
    "examDuration": 15,
    "links": {
        "VII": {
            "ips": "",
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "ipa": "",
            "informatika": "",
            "senibudaya": "",
            "pjok": "",
            "prakarya": "",
            "mapel_lain_1": "",
            "mapel_lain_2": ""
        },
        "VIII": {
            "ips": "https://docs.google.com/forms/d/e/1FAIpQLSdgZLoM9Ev_rdpNv9Y6EDOdPPF972nPjl_e_9pCkqZMpZuG1A/viewform?usp=header",
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "ipa": "",
            "informatika": "",
            "senibudaya": "",
            "pjok": "",
            "prakarya": "",
            "mapel_lain_1": "",
            "mapel_lain_2": ""
        },
        "IX": {
            "ips": "masukan link di sini",
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "ipa": "",
            "informatika": "",
            "senibudaya": "https://docs.google.com/forms/d/e/1FAIpQLSd1wW-xhrFB2GM8y9BhP0IppZehG095TZsi_R2BOvMrgioyyw/viewform?usp=sharing",
            "pjok": "",
            "prakarya": "",
            "mapel_lain_1": "",
            "mapel_lain_2": ""
        },
        "X": {
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "ipa": "",
            "ips": "",
            "sejarah": "",
            "informatika": "",
            "senibudaya": "",
            "pjok": "",
            "prakarya": "",
            "fisika": "",
            "kimia": "",
            "biologi": "",
            "ekonomi": "",
            "sosiologi": "",
            "geografi": "",
            "mulok_1": "",
            "mulok_2": "",
            "mapel_lain_1": "",
            "mapel_lain_2": ""
        },
        "XI": {
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "sejarah": "",
            "pjok": "",
            "senibudaya": "",
            "fisika": "",
            "kimia": "",
            "biologi": "",
            "ekonomi": "",
            "sosiologi": "",
            "geografi": "",
            "sejarah_peminatan": "",
            "tik": "",
            "jurusan_1": "",
            "jurusan_2": "",
            "mapel_lain_1": "",
            "mapel_lain_2": "",
            "ips": "https://docs.google.com/forms/d/e/1FAIpQLSdgZLoM9Ev_rdpNv9Y6EDOdPPF972nPjl_e_9pCkqZMpZuG1A/viewform?usp=header"
        },
        "XII": {
            "pabp": "",
            "pancasila": "",
            "bindo": "",
            "bing": "",
            "matematika": "",
            "sejarah": "",
            "pjok": "",
            "senibudaya": "",
            "fisika": "",
            "kimia": "",
            "biologi": "",
            "ekonomi": "",
            "sosiologi": "",
            "geografi": "",
            "sejarah_peminatan": "",
            "tik": "",
            "jurusan_1": "",
            "jurusan_2": "",
            "mapel_lain_1": "",
            "mapel_lain_2": ""
        }
    }
};